# Light profile synced from Konsole (Light.profile -> Materia.colorscheme)
font-family = Iosevka Fixed
font-size = 11
background = #eeeeee
foreground = #000000
selection-foreground = #f9f9f9
selection-background = #000000
cursor-color = #000000
cursor-text = #f9f9f9
cursor-style = block
cursor-style-blink = false

palette = 0=#000000
palette = 1=#f44336
palette = 2=#2e7d32
palette = 3=#ff9800
palette = 4=#408deb
palette = 5=#f806fa
palette = 6=#1b969c
palette = 7=#ffffff
palette = 8=#000000
palette = 9=#f44336
palette = 10=#6ab538
palette = 11=#ff9800
palette = 12=#3048d1
palette = 13=#f806fa
palette = 14=#1a7381
palette = 15=#ffffff

background-opacity = 0.7
confirm-close-surface = false
window-padding-x = 4
window-padding-y = 4
keybind = ctrl+shift+t=new_tab

# GTK tabbar styling (adapted from Konsole tabbar)
window-show-tab-bar = auto
#gtk-titlebar-style = tabs
gtk-tabs-location = bottom
gtk-wide-tabs = false
gtk-custom-css = /home/wilf/.config/HyprV/ghostty/ghostty-tabbar.css
