#!/usr/bin/env bash

iDIR="$HOME/.config/HyprV/mako/icons"

# Get brightness
#get_backlight() {
#	LIGHT=$(printf "%.0f\n" $(brightnessctl i))
#	echo "${LIGHT}%"
#}

# Get icons
get_icon() {
	backlight="$(brightnessctl g)"
	current="${backlight%%%}"
	if [[ ("$current" -ge "0") && ("$current" -le "42") ]]; then
		icon="$iDIR/brightness-20.png"
	elif [[ ("$current" -ge "43") && ("$current" -le "81") ]]; then
		icon="$iDIR/brightness-40.png"
	elif [[ ("$current" -ge "81") && ("$current" -le "153") ]]; then
		icon="$iDIR/brightness-60.png"
	elif [[ ("$current" -ge "154") && ("$current" -le "290") ]]; then
		icon="$iDIR/brightness-80.png"
	elif [[ ("$current" -ge "291") && ("$current" -le "600") ]]; then
		icon="$iDIR/brightness-100.png"
	fi
}

# Exponential operations


# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Brightness : $(brightnessctl g)"
}

# Increase brightness
inc_backlight() {
	brightnessctl set 1%+ && get_icon && notify_user 
}

# Decrease brightness
dec_backlight() {
	brightnessctl set 1%- && get_icon && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	brightnessctl g
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	echo failed
fi
